ICT-Dev-Route/Dev-Route-BE

- .idea/.gitignore
- .idea/Dev-Route-BE.iml
- .idea/compiler.xml
- .idea/gradle.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/dummy.java
> Feat: package initial

- .idea/Dev-Route-BE.iml
- .idea/gradle.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/modules/dev-route.main.iml
- .idea/uiDesigner.xml
- dev-route/.gitignore
- dev-route/build.gradle
- dev-route/src/main/java/com/teamdevroute/devroute/DevRouteApplication.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/BaseEntity.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/Recruitment.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/AuthToken.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/User.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/enums/DevelopField.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/enums/LoginType.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/enums/UserRole.java
.idea를 .gitignore에 선언하는 걸 뒤늦게 해서 이번 PR까지 포함하겠습니다..
> Add Entities of User Package and Recruitment Package

- .idea/gradle.xml
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/Roadmap_step.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/Roadmap_step_info.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/dummy.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/Technology_stack.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/Videos.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/dummy.java
Add Entity of RoadMap Package And Video Package
> Add Entity of RoadMap Package And Video Package

- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapStep.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapStepInfo.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/TechnologyStack.java
- dev-route/src/main/resources/application.properties
> Modify package name

- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapStep.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapStepInfo.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/TechnologyStack.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/Videos.java
Refactor: Entity내의 GeneratedValue strategy 설정
> Refactor: Entity내의 GeneratedValue strategy 설정

- dev-route/build.gradle
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/WebDriverUtil.java
- dev-route/src/main/resources/application.properties
- dev-route/src/test/java/com/teamdevroute/devroute/crawling/CrawlingTest.java
- 직접 크롬드라이버 설치 필요없이 WebDriverManager를 사용
- 크롤링 도메인 패키지 추가
- Jsoup, Selenium 버전 업데이트
<br/>
- 상위 30개 기업 받아오기
- secretKey 서브모듈로 추가
<br/>
<br/>
> feat: 크롤링 초기 셋팅

- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawlingService.java
- dev-route/src/test/java/com/teamdevroute/devroute/crawling/CrawlingTest.java
- 기존 상위 30개 기업 크롤링에 로고 추가
- 테스트 코드 통과 완료
<br/>
- 상위 30개 기업 상세 정보 크롤링
<br/>
<br/>
> fix(#25): 상위 30개 기업 로고 크롤링 추가

- dev-route/src/main/java/com/teamdevroute/devroute/DataLoader.java
- 프로덕션용 더미 데이터 추가
<br/>
- 
<br/>
<br/>
> chore(#..): 프로덕션용 더미 데이터 추가

- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapController.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapService.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/domain/RoadmapStep.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/domain/RoadmapStepInfo.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/dto/DetailedRoadmapResponseDTO.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/dto/RoadmapResponseDTO.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/Repository/TechnologyStackRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/Repository/VideoRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoController.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoService.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/domain/TechnologyStack.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/dto/LectureResponseDTO.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/dto/infrean/InfreanVideoDTO.java
- dev-route/src/test/java/com/teamdevroute/devroute/crawling/VideoCrawlingTest.java
- dev-route/src/test/java/com/teamdevroute/devroute/video/VideoServiceTest.java
- VideoCrawlling관련 테스트 코드 작성.
- 영상별 기술 스택을 선택시 TechnologyStack db에 count+ 기능 구현
- Roadmap패키지 내에 dto,service,controller 추가(구현x)
<br/>
- roadmap db에 들어갈 내용 확정되면 서비스 로직 작성
- 로드맵 관련 단위테스트 작성
<br/>
<br/>
> [#30,#37]: Test: Add VideoCrawlling Test Code,영상별 기술 스택을 선택시 db에 count+ 기능 구현

- dev-route/src/main/java/com/teamdevroute/devroute/global/exception/DuplicateUserException.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserControllerAdvice.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserService.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/domain/User.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/dto/UserCreateRequest.java
- 유저 회원가입 시, 비밀번호 인코드 하지 않고 저장한 문제 해결
- 유저 회원가입 시 같은 이메일로 중복 회원가입되는 문제 해결
<br/>
<br/>
<br/>
> [#43 & #44] fix: 중복회원가입 및 로그인 안되는 버그 해결

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/domain/Recruitment.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/enums/DevelopmentField.java
- cors 접근 오류 해결
<br/>
<br/>
<br/>
> [#35] fix : cors 접근 오류 해결

- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/CustomAuthenticationEntryPoint.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/filter/JwtAuthFilter.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/exception/InvalidAccessException.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserControllerAdvice.java
- CustomAuthenticationEntryPoint 수정 -> 200 및 "접근 권한이 없습니다." 반환
<br/>
<br/>
<br/>
> [#46] fix: 권한 없는 경우, 200 및 빈 페이지 뜨는 버그 수정

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
- 토큰 헤더 -> 토큰 세션으로 관리
<br/>
<br/>
<br/>
> [#47]fix : token 오류 해결

- dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCount.java
- dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCountController.java
- dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCountRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCountResponse.java
- dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCountService.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- 방문자수를 받아오는 API를 type 별로 수정
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> [#33] fix: 방문자수를 받아오는 API 수정

- dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
- JWT 방식을 세션으로 변경
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> [#49] fix: JWT 방식을 세션으로 변경

- dev-route/src/main/java/com/teamdevroute/devroute/user/UserService.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/dto/UserCreateRequest.java
- 회원가입 시 DevelopField Default값 NONE 설정
<br/>
<br/>
<br/>
> [#51]feat : 회원가입 시 DevelopField Default값 NONE 설정

- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/InfreanVideoCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/WebDriverUtil.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapController.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapService.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/description/Ai.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/description/Backend.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/description/Frontend.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/description/Mobile.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/domain/RoadmapStep.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/domain/RoadmapStepInfo.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/dto/DetailedRoadmapResponseDTO.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/repository/RoadmapStepInfoRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/repository/RoadmapStepRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoService.java
- dev-route/src/test/java/com/teamdevroute/devroute/crawling/VideoCrawlingTest.java
- dev-route/src/test/java/com/teamdevroute/devroute/user/UserFixture.java
- 개발 분야별 로드맵 정보를 제공
- 개발 상세 로드맵 정보 저장
- 개발 분야 및 단계 별 상세로드맵 정보를 제공 
- 개발 로드맵 상세 정보의 경우 연관 기술 스택과 연관 기업, 그리고 기술 스택 비율이 미정인 관계로 null로 처리함.
<br/>
- 단위 테스트 코드 작성하기 및 리펙토링
- NULL로 처리한 값들 수정해야함
<br/>
<br/>
> [#52] feat: 개발 분야별 로드맵 정보를 제공,[#53&54] feat: 개발 상세 로드맵 정보 저장 및 개발 분야 및 단계 별 상세로드맵 정보를 제공

- dev-route/src/main/java/com/teamdevroute/devroute/crawling/InfreanVideoCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapController.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapService.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/enums/DevelopmentField.java
- 기능에서 어떤 부분이
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> [#30] feat:영상 관련 api,크롤링 관련 버그 잡기

- dev-route/build.gradle
- dev-route/src/main/java/com/teamdevroute/devroute/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/TestDataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/controller/CompanyController.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/domain/Company.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/dto/CompanyResponse.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/repository/CompanyRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/service/CompanyService.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawlingService.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawlingService.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/dto/CrawledRecruitmentDto.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/controller/RecruitmentController.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/domain/Recruitment.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentService.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentUpdateService.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapService.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/domain/RoadmapStepInfo.java
- dev-route/src/main/resources/application.properties
- dev-route/src/main/resources/data.sql
- dev-route/src/test/java/com/teamdevroute/devroute/company/CompanyServiceTest.java
- TestDataLoader에 회사 더미테이터 추가
- 받아오는 정보: 로고주소, 이름, 채용공고 수, 평점, 연봉
<br/>
- 기업 상세 정보 조회
- 채용공고 검색
<br/>
<br/>
> [#58] feat: 상위 30개 모든 기업의 간단정보를 조회

- dev-route/src/main/java/com/teamdevroute/devroute/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/TestDataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/controller/RecruitmentController.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/domain/Recruitment.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/repository/RecruitmentRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentService.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/enums/DevelopField.java
- dev-route/src/test/java/com/teamdevroute/devroute/recruitment/RecruitmentServiceTest.java
- type을 쿼리 파라미터로 받아 각 직종의 채용공고 검색
- type이 이상할 경우, IllegalArgumentException 발생
- 테스트 코드 통과
<br/>
<br/>
<br/>
> [#59] feat: 직종별 채용공고 검색

- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/jwt/JwtUtils.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
feat(#63): 로그인 시 회원정보 CustomUserDetails로 받아오는 기능 추가
- 로그인 시 userDetails 가져오기
- userDetails로 회원정보 바로 조회
<br/>
- 직군별 스택 통계화
<br/>
<br/>
> [#63]feat :  로그인 시 회원정보 CustomUserDetails로 받아오는 기능 추가

- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkController.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkFindRequest.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkFindResponse.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkService.java
- 유저 id를 기반으로 해당 유저의 북마크 정보를 반환
- 북마크의 모든 데이터를 한 번에 반환
<br/>
- 더미데이터 더 추가
- 북마크 조회 API 명세서 Response 수정
<br/>
<br/>
> [#62]feat: 유저 id 기반 북마크 내역 조회

- dev-route/src/main/java/com/teamdevroute/devroute/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/Bookmark.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkService.java
- 기술스택은 로드맵 생성 시 만들어짐
- 따라서, 별도의 기술스택 대신 로드맵의 기술스택을 이용
- 포스트맨 테스트 성공
<br/>
- 더미 데이터 추가
<br/>
<br/>
> [#69]fix: 북마크 기능에 기술스택 삭제

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/controller/RecruitmentController.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/domain/Recruitment.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/dto/TechStackFrequencyDto.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/enums/DevelopmentField.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/enums/SearchKeyWord.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/repository/RecruitmentRepository.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentService.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentUpdateService.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/utils/TechnologyStackCategory.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/enums/DevelopField.java
- 채용 공고 분석
- 개발 분야별 기술 스택을 분류하여 % 분류
<br/>
- 마이 페이지 가져오기
- 마이 페이지 수정
<br/>
<br/>
> [#35]feat : 직군별 기술스택 시각화 api 개발

- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/Bookmark.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkController.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkDeleteRequest.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkService.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserService.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/domain/User.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/dto/UserMyPageResponse.java
- mypage 조회
- 북마크 삭제 기능 추가
<br/>
<br/>
<br/>
> [#75]feat : mypage 조회 및 마이페이지 북마크 삭제

- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkController.java
- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkFindRequest.java
- 북마크 조회 시, UserId를 body에서 받도록 수정
<br/>
<br/>
<br/>
> [#75]fix: 북마크 조회 시, UserId를 body에서 받도록 수정

- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/controller/RecruitmentController.java
- 기술스택 api 수정
<br/>
<br/>
<br/>
> [#35]fix : 기술스택 시각화 api 수정

- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkService.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserService.java
- 순환 참조를 해결하기 위해 UserService -> BookmarkService, BookmarkService -> UserRepository를 사용하도록 수정
<br/>
<br/>
> [#76]fix: 회원가입 시, User의 Bookmark를 생성하도록 수정

- dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
- 세션 사용 시, 받아지지 않는 버그 발생
<br/>
<br/>
<br/>
> [#77] fix: User 로그인 시, 토큰을 Session 대신 Header 를 이용하여 반환

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- Authorization 헤더가 안받아지는 오류 해결
<br/>
<br/>
<br/>
> [#78] fix: Authorization 헤더가 안받아지는 오류 해결

- dev-route/src/main/java/com/teamdevroute/devroute/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoController.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoService.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/dto/LectureResponseDTO.java
> fix: 강의 반환 DTO에 강의 ID 값 추가 / test: 강의 영상 더미데이터 대량 추가 / fix: url 화이트 리스트에서 강의 관련 url 수정

- dev-route/src/main/java/com/teamdevroute/devroute/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/TestDataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/dto/CompanyDetailRecruitResponse.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/dto/CompanyDetailResponse.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/domain/Recruitment.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/dto/RecruitmentFindResponse.java
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentUpdateService.java
- 채용공고의 dueDate를 LocalDateTiem에서 LocalDate로 변경
<br/>
<br/>
<br/>
> fix: 채용공고의 dueDate를 LocalDateTiem에서 LocalDate로 변경

- dev-route/src/main/java/com/teamdevroute/devroute/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/filter/JwtAuthFilter.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/service/CustomUserDetailsService.java
- UserDetails에서 CustomUserDetail로 변경
<br/>
<br/>
<br/>
> fix: JwtAuthFilter에서 loadUserByUsername의 반환 타입 변경

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/config/WebConfig.java
> security: allowedOrigins -> allowedOriginPatterns

- dev-route/Dockerfile
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/domain/Recruitment.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapController.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/dto/RoadmapResponseDTO.java
- fix roadmap dto
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix roadmap dto

- dev-route/compose.yml
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoController.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/dto/TechStackDTO.java
-  강의 영상 기술 스택 보내주기
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> [#30] feat: 강의 영상 기술 스택 보내주기

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoController.java
- 기능에서 어떤 부분이
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> cors 오류 해결

- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkController.java
- bookmark add를 post에서 get으로 수정
<br/>
<br/>
<br/>
> fix: bookmark add를 post에서 get으로 수정

- dev-route/src/main/java/com/teamdevroute/devroute/company/dto/CompanyDetailResponse.java
docs- 제목 : feat(issue 번호): 기능명
- ex) 
feat(#17): pull request template 작성
**[ 확인 후 지워주세요 ]**
| 타입 이름     | 내용                               |
|-----------|----------------------------------|
| **feat**  | 새로운 기능에 대한 커밋                    |
| **fix**   | 	버그 수정에 대한 커밋                    |
| **build** | 	빌드 관련 파일 수정 / 모듈 설치 또는 삭제에 대한 커 |
| **chore** | 	그 외 자잘한 수정에 대한 커밋               |
| **ci**    | 	ci 관련 설정 수정에 대한 커밋              |
| **docs**  | 	문서 수정에 대한 커밋                    |
| **style** | 	코드 스타일 혹은 포맷 등에 관한 커밋           |
| **refactor** |	코드 리팩토링에 대한 커밋|
| **test**  |	테스트 코드 수정에 대한 커밋|
| **perf**  |	성능 개선에 대한 커밋|
- 기능에서 어떤 부분이
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: 기업 상세조회에서 id값 반환하도록 추가

- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/Bookmark.java
- bookmark의 companies, videos, roadmaps 저장 타입 varchar -> text로 수정
<br/>
<br/>
<br/>
> [#79]fix : Bookmark 저장 타입 오류 수정

- dev-route/src/main/java/com/teamdevroute/devroute/dataloader/RecruitmentDataLoader.java
- 단순히 테스트 용도 이므로, 프로덕션 단계에서 삭제 예정
<br/>
- 인프라 구축
<br/>
<br/>
> test: 상위 30개 기업의 채용공고 테스트 데이터 삽입

- .github/workflows/deploy.yml
- 초기 CI/CD 설정
자바 빌드 -> 도커 이미지 생성 -> 도커허브 푸시 -> ec2 ssh 접속 -> 도커 이미지 풀 -> 컨테이너 생성
<br/>
<br/>
<br/>
> cicd: CI/CD 초기 설정

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
- 로드밸런서 체크 api
<br/>
<br/>
<br/>
> [#82]feat: 로드밸런서 체크 api 추가

- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapController.java
- dev-route/src/main/java/com/teamdevroute/devroute/roadmap/RoadmapService.java
docs- 제목 : feat(issue 번호): 기능명
- ex) 
feat(#17): pull request template 작성
**[ 확인 후 지워주세요 ]**
| 타입 이름     | 내용                               |
|-----------|----------------------------------|
| **feat**  | 새로운 기능에 대한 커밋                    |
| **fix**   | 	버그 수정에 대한 커밋                    |
| **build** | 	빌드 관련 파일 수정 / 모듈 설치 또는 삭제에 대한 커 |
| **chore** | 	그 외 자잘한 수정에 대한 커밋               |
| **ci**    | 	ci 관련 설정 수정에 대한 커밋              |
| **docs**  | 	문서 수정에 대한 커밋                    |
| **style** | 	코드 스타일 혹은 포맷 등에 관한 커밋           |
| **refactor** |	코드 리팩토링에 대한 커밋|
| **test**  |	테스트 코드 수정에 대한 커밋|
| **perf**  |	성능 개선에 대한 커밋|
- 기능에서 어떤 부분이
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: 로드맵 관련 수정

- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyRecruitmentCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawlingService.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/WebDriverUtil.java
- crawling 관련 버그 수정 
- ec2에서 cpu 과열 이슈 해결
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: crawling 관련 버그 수정 및 ec2에서 cpu 과열 이슈 해결

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- requiresChannel.requiresSecure()
- httpStrictTransportSecurity.hsts
<br/>
<br/>
<br/>
> security: Https 관련 header 추가

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- Https 가 https로 리다이렉트되는 문제 해결
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> security: ForwardedHeaderFilter 추가

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- 기능에서 어떤 부분이
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: CORS URL을 https://devroute.site로 변경

- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoController.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/service/VideoService.java
- video @scheduled 수정
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> [#84] fix: video @scheduled 수정

- dev-route/src/main/java/com/teamdevroute/devroute/dataloader/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/service/VideoService.java
- @scheduled 수정
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: @scheduled 수정

- dev-route/src/main/java/com/teamdevroute/devroute/video/service/VideoService.java
-  @scheduled 수정
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> [#84] fix: @scheduled 수정

- dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
- cors 해결
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> [#45]fix: cors 해결

- dev-route/src/main/java/com/teamdevroute/devroute/dataloader/DataLoader.java
- dataLoader 문제 해결
<br/>
- dataLoader 문제 해결
- 적어주세요
<br/>
<br/>
> [#87] fix: dataLoader 문제 해결

- dev-route/build.gradle
- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/filter/JwtAuthFilter.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/auth/jwt/JwtUtils.java
- dev-route/src/main/java/com/teamdevroute/devroute/user/UserService.java
- 프론트와의 cors오류 해결
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: cors오류 해결

- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyRecruitmentCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/dataloader/DataLoader.java
- CommandLinner를 상속한 DataLoader에서 User를 실행 시 생성하는 코드로 인한 서버 실행 불가 발생
- `if(findBy..())` 를 사용하여 기존 정보가 있는지 확인하도록 수정
<br/>
- 운영 단계에선 이 부분을 삭제 후, 운영하는 것이 올바르다고 생각된다.
- 따라서, 프로메테우스 테스트 후 DataLoader와 관련된 코드를 삭제할 예정이다.
<br/>
<br/>
> fix: CommandLinner에 의한 중복 데이터 삽입 문제 해결

- dev-route/src/main/java/com/teamdevroute/devroute/company/service/CompanyService.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawlingService.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawling.java
- 점핏 페이지 변경에 따른 코드 수정
- 검색창을 이용하여 크롤링 진행
<br/>
- 크롤링 중복 문제 체크 및 수정
<br/>
<br/>
> fix: 상위 30개 기업 채용공고 크롤링이 정상적이지 않던 문제 해결

- dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkController.java
- dev-route/src/main/java/com/teamdevroute/devroute/company/controller/CompanyController.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyRecruitmentCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/crawling/WebDriverUtil.java
- dev-route/src/main/java/com/teamdevroute/devroute/dataloader/BookmarkDataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/aop/crawl/Crawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/aop/crawl/CrawlingAspect.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/aop/timetrace/TimeTrace.java
- dev-route/src/main/java/com/teamdevroute/devroute/global/aop/timetrace/TimeTraceAspect.java
Selenium을 통해 현재 크롤링이 진행된다. 크롤링을하기 위해 Selenium의 Chorme Driver를 @PostStructure을 통해 Setup 하도록 설계되어있다.
```java
@Component
@Getter
public class WebDriverUtil {
private WebDriver driver;
@PostConstruct
public void setUpDriver(){
WebDriverManager.chromedriver().setup();
}
public void getChromeDriver(String url) {
if (driver == null) {
ChromeOptions chromeOptions = new ChromeOptions();
setChromeOption(chromeOptions);
driver = new ChromeDriver(chromeOptions);
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
}
Set<Cookie> cookies = driver.manage().getCookies();
for (Cookie cookie : cookies) {
driver.manage().addCookie(cookie);
}
driver.get(url);
}
// 생략
}
```
Setup을 하게되면 그 순간 chromdriver가 실행되고, 그 이후 getChromeDriver(url)을 통해 받은 정보를 기반으로 크롤링을 수행한다.
현재 코드에선 채용공고와 기업, 강의에 대한 크롤링이 매주 …
> feat: AOP를 이용한 Selenium 메모리 사용량 감소를 통한 성능 최적화

- dev-route/src/main/java/com/teamdevroute/devroute/crawling/InfreanVideoCrawling.java
- dev-route/src/main/java/com/teamdevroute/devroute/dataloader/DataLoader.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/VideoController.java
- dev-route/src/main/java/com/teamdevroute/devroute/video/service/VideoService.java
- dev-route/src/main/resources/application.properties
- Refactor: videoCrawling 관련 리팩토링 및 techstack이 중복되는 오류 해결
<br/>
- 내일 할 일을
- 적어주세요
<br/>
-  [Refactor: videoCrawling 관련 리팩토링 및 techstack이 중복되는 오류 해결](https://github.com/ICT-Dev-Route/Dev-Route-BE/commit/843e75088a09ddef034f1cc5d7aa982d7ccf74cf)
<br/>
> Refactor: videoCrawling 관련 리팩토링 및 techstack이 중복되는 오류 해결

- .github/workflows/deploy.yml
- CI/CD에 prod적용 안되는 것 수정
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> Refactor:Update deploy.yml

- .github/workflows/deploy.yml
- dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentUpdateService.java
- dev-route/src/main/resources/application-dev.properties
- dev-route/src/main/resources/application.properties
- dev-route/src/test/java/com/teamdevroute/devroute/recruitment/RecruitmentUpdateServiceTest.java
-  사람인 api를 통해서 response를 잘 반환하는지 테스트 코드 작성
- api요청이 한계치를 넘 었을 때에 대한 예외 처리
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [레포 이름 #이슈번호](이슈 주소)](https://github.com/ICT-Dev-Route/Dev-Route-BE/issues/125)
<br/>
> test&refactor: 사람인 api를 통해서 response를 잘 반환하는지 테스트 코드 작성 및 api요청이 한계치를 넘   었을 때에 대한 예외 처리

- .github/workflows/deploy.yml
- CI/CD에서 cache 사용 
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> refactor: CI/CD에서 cache 사용 

- .github/workflows/deploy.yml
- dev-route/src/main/resources/application-dev.properties
- dev-route/src/main/resources/application-prod.properties
- dev-route/src/main/resources/application.properties
- gradle 의존성 캐시 추가
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [#125](https://github.com/ICT-Dev-Route/Dev-Route-BE/issues/125)
<br/>
> refactor: gradle파일을 CI/CD에서 캐싱해서 사용할 수 있게 적용
