ICT-Dev-Route/Dev-Route-BE

.gitmodules
dev-route/.gitignore
dev-route/build.gradle
dev-route/src/main/java/com/teamdevroute/devroute/TestDataLoader.java
dev-route/src/main/java/com/teamdevroute/devroute/global/auth/AuthorizationProvider.java
dev-route/src/main/java/com/teamdevroute/devroute/global/auth/CustomAccessDeniedHandler.java
dev-route/src/main/java/com/teamdevroute/devroute/global/auth/CustomAuthenticationEntryPoint.java
dev-route/src/main/java/com/teamdevroute/devroute/global/auth/LoginUserInfo.java
dev-route/src/main/java/com/teamdevroute/devroute/global/auth/UserAuthContext.java
dev-route/src/main/java/com/teamdevroute/devroute/global/auth/filter/JwtAuthFilter.java
dev-route/src/main/java/com/teamdevroute/devroute/global/auth/jwt/JwtUtils.java
dev-route/src/main/java/com/teamdevroute/devroute/global/config/PasswordEncoderConfig.java
dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
dev-route/src/main/java/com/teamdevroute/devroute/global/exception/UserNotFoundException.java
dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
dev-route/src/main/java/com/teamdevroute/devroute/user/UserControllerAdvice.java
dev-route/src/main/java/com/teamdevroute/devroute/user/UserLoginRequest.java
dev-route/src/main/java/com/teamdevroute/devroute/user/UserRepository.java
dev-route/src/main/java/com/teamdevroute/devroute/user/UserService.java
dev-route/src/main/java/com/teamdevroute/devroute/user/domain/CustomUserDetails.java
dev-route/src/main/java/com/teamdevroute/devroute/user/service/CustomUserDetailsService.java
dev-route/src/main/resources/application.properties

- jwt secretket와 만료시간 등을 저장하는 `Submodule` 추가
- `Spring Security` 추가
- Jwt용 `Filter` 추가
- `Security Config` 추가
- `WHITELIST_URL`을 통해 인증이 필요없는 url 설정
1. `MemberAuthContext`: 유저의 인증을 위한 정보를 저장
2. `JwtAuthFilter`: 요청에 담긴 jwt를 검증하여 userDetail 생성 및 현재 요청의 접근 허용
3. `JwtUtil`: Jwt 토큰 생성 및 Validation
4. `AuthorizationProvider`: JwtUtil의 인터페이스
5. `CustomAccessDeniedHandler`: 액서스 거부 시 핸들러 (SecurityConfig에서 설정)
6. `CustomAuthenticationEntryPoint`: 엔트리 포인트의 인증 예외처리
7. `SecurityConfig`: 스프링 시큐리티 설정
8. `MemberControllerAdvice`: Member 도메인 컨트롤러의 예외처리 통합 관리
<br/>
- SSO 로그인 구현
<br/>
<br/>

feat(#26, #27): Spring Security 기반 JWT 로그인 + Submodule 적용

---

dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawling.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/dto/CrawledRecruitmentDto.java
dev-route/src/main/resources/data.sql
dev-route/src/test/java/com/teamdevroute/devroute/crawling/CrawlingTest.java
dev-route/src/test/java/com/teamdevroute/devroute/user/UserServiceTest.java

- 기업 이름을 기반으로 점핏에서 채용공고를 크롤링
- RecruitmentCrawling에서 채용공고 크롤링 진행
- ❗ **데이터 베이스에 저장되는 코드는 미포함**
<br/>
- 크롤링 코드 리펙터링
- 크롤링된 코드 DB에 저장하는 로직
- @Scheduled 사용하기
<br/>
<br/>

[#25]feat: 기업 이름 기반 점핏 채용공고 크롤링

---

dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawling.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyCrawlingService.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyRecruitmentCrawling.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawling.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawlingService.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/dto/CrawledCompanyDto.java
dev-route/src/test/java/com/teamdevroute/devroute/crawling/CrawlingTest.java

- `CompanyCrawling`과 `RecruitmentCrawling` 에서 **각 크롤링 기능 모듈화**
- `CompanyRecruitmentCrawling`에서 **모듈화된 크롤링 기능을 한 번에 수행**
- `@Scheduled`를 통해 **매일 자정 업데이트 되도록 수정**
- `CrawledCompanyDto`와 `CrawledRecruitmentDto`에서 크롤링된 정보를 가짐
<br/>
- Recruitment 엔티티 어트리뷰트 수정
<br/>
<br/>

[#25]feat: 상위 30개 기업 검색 후, 검색 결과로 채용공고 검색

---

dev-route/src/main/java/com/teamdevroute/devroute/global/auth/Oauth2Util.java
dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java
dev-route/src/main/java/com/teamdevroute/devroute/user/UserController.java
dev-route/src/main/java/com/teamdevroute/devroute/user/UserService.java

- naver, google 로그인 추가
- 가입 되지 않은 회원이면 db 저장하기
- 가입된 회원이면 access 토큰 발급 후 로그인
- sso 관련 모든 key secret으로 설정
<br/>
- 채용 정보 시각화
<br/>
<br/>

[#34] feat : naver, google 로그인 구현

---

dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCount.java
dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCountRepository.java
dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCountResponse.java
dev-route/src/main/java/com/teamdevroute/devroute/api/visitorcount/VisitorCountService.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyRecruitmentCrawling.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/RecruitmentCrawlingService.java
dev-route/src/main/java/com/teamdevroute/devroute/crawling/dto/CrawledRecruitmentDto.java
dev-route/src/main/java/com/teamdevroute/devroute/global/exception/CompanyNotFoundException.java
dev-route/src/main/java/com/teamdevroute/devroute/recruitment/enums/Source.java
dev-route/src/main/java/com/teamdevroute/devroute/user/domain/User.java
dev-route/src/test/java/com/teamdevroute/devroute/user/UserFixture.java
dev-route/src/test/java/com/teamdevroute/devroute/visitorcount/VisitorCountServiceTest.java

- 기존 크롤링된 채용공고를 DB에 저장하는 로직 추가
- 회사의 이름을 바탕으로 저장된 회사를 검색
- 불러오기의 경우, (0, 오늘), (1, 일주일간), (2, 월간) 타입을 쿼리 파라미터로 받아서 처리
<br/>
- 채용공고의 URL 및 마감일자 받아오기
<br/>
<br/>

[#55] fix: 크롤링된 채용공고를 DB에 저장 /  [#33] feat: 방문자 수 업데이트 및 불러오기

---

dev-route/src/main/java/com/teamdevroute/devroute/api/suggestion/SuggestionCategory.java
dev-route/src/main/java/com/teamdevroute/devroute/api/suggestion/SuggestionController.java
dev-route/src/main/java/com/teamdevroute/devroute/api/suggestion/SuggestionCreateRequest.java
dev-route/src/main/java/com/teamdevroute/devroute/api/suggestion/SuggestionRepository.java
dev-route/src/main/java/com/teamdevroute/devroute/api/suggestion/SuggestionService.java
dev-route/src/main/java/com/teamdevroute/devroute/api/suggestion/SuggestionStatus.java
dev-route/src/main/java/com/teamdevroute/devroute/api/suggestion/Suggestions.java
dev-route/src/test/java/com/teamdevroute/devroute/suggestions/SuggestionServiceTest.java
src/Main.java

- 건의사항을 저장하는 Suggestions 엔티티 (Suggestion 이라는 클래스가 이미 외부 라이브러리에서 사용 중이라 s를 붙임)
- 건의사항 카테고리는 `에러사항`( REPORT_ERROR), `건의사항` (REPORT_SUGGEST) 이 존재
- 건의사항 내용이 빈 경우, `IllegalArgumentException` 발생
<br/>
- 유저 정보를 받아오는 `@AuthenticationPrincipal` 대신 어떤 것을 사용해야 하는지
<br/>
<br/>

[#56] feat: 건의사항을 업로드

---

dev-route/src/main/java/com/teamdevroute/devroute/company/CompanyControllerAdvice.java
dev-route/src/main/java/com/teamdevroute/devroute/company/controller/CompanyController.java
dev-route/src/main/java/com/teamdevroute/devroute/company/dto/CompanyDetailRecruitResponse.java
dev-route/src/main/java/com/teamdevroute/devroute/company/dto/CompanyDetailResponse.java
dev-route/src/main/java/com/teamdevroute/devroute/company/service/CompanyService.java
dev-route/src/main/java/com/teamdevroute/devroute/recruitment/repository/RecruitmentRepository.java
dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentService.java

- `company_id`를 이용하여 해당 기업의 상세 정보 조회
- 전달하는 정보: 이름, 소개말, 평점, 평균연봉, 모든 채용공고들
- 
- `Recruitment`와 `Company`의 **양방향 매핑**으로 인해 Company에서 Recuritment 반환 시, Recruitment에서 Company 반환이 무한이 반복되는 이슈가 발생
- 이를 해결하기 위해 Company에서 Recuritment 반환 대신, `별도의 dto`를 이용하여 양방향 연관관계는 반환하지 않도록 수정
<br/>
<br/>
<br/>

[#70]feat: 기업 소개 및 해당 기업 공고글 조회 / [#71]fix: #70번 이슈 해결 

---

dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkController.java
dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkService.java
dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkUpdateRequest.java
dev-route/src/test/java/com/teamdevroute/devroute/bookmark/BookmarkServiceTest.java

- 쿼리파라미터로 유저의 id를 입력받는 대신, body로 유저의 id를 받도록 수정
- Post의 경우, 쿼리 파라미터를 사용하기 보단 안전한 body를 이용
<br/>
- 인프라 구축 시작
<br/>
<br/>

[#73]fix: 북마크 등록 API의 유저 정보 수정

---

dev-route/src/main/java/com/teamdevroute/devroute/recruitment/controller/RecruitmentController.java
dev-route/src/main/java/com/teamdevroute/devroute/recruitment/dto/RecruitmentFindResponse.java
dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentService.java
dev-route/src/test/java/com/teamdevroute/devroute/recruitment/RecruitmentServiceTest.java

- Recruitment 안에 있는 Company가 호출되고, Company 안에 있는 Recruitment가 호출
- 위 현상이 무한히 반복되는 문제 발생
- API 콜에서 Recruitment를 바로 반환하는 것이 아닌 별도의 DTO인 RecruitmentFindResponse를 반환하도록 수정
<br/>
<br/>

[#74]fix: 직종별 채용공고 검색 시, Recuritment와 Company가 서로를 의존하면 무한히 반복되는 현상

---

dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkController.java
dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkService.java
dev-route/src/main/java/com/teamdevroute/devroute/bookmark/BookmarkUpdateRequest.java
dev-route/src/test/java/com/teamdevroute/devroute/bookmark/BookmarkServiceTest.java

- 북마크의 유저id를 받는 대신 @AuthenticationPrincipal 이용하도록 수정
<br/>
<br/>
<br/>

[#79] fix: 북마크의 유저id를 받는 대신 @AuthenticationPrincipal 이용하도록 수정

---

dev-route/src/main/java/com/teamdevroute/devroute/company/dto/CompanyResponse.java

- 상세 정보 조회를 위한 id 값이 필요
<br/>
<br/>
<br/>

[#80] fix: 기업 검색 시, 해당 기업의 id도 반환하도록 수정

---

dev-route/src/main/java/com/teamdevroute/devroute/global/config/WebConfig.java

- WebMvcConfigurer의 addCorsMappings를 구현하여 localhost:3000를 origin으로 허용
<br/>
<br/>
<br/>

fix: CORS 해결을 위한 WebConfig 추가

---

dev-route/src/main/java/com/teamdevroute/devroute/dataloader/CompanyDataLoader.java
dev-route/src/main/java/com/teamdevroute/devroute/dataloader/DataLoader.java
dev-route/src/main/java/com/teamdevroute/devroute/dataloader/RecruitmentDataLoader.java

- DataLoader에서 CompanyDataLoader와 RecruitmentDataLoader로 각 데이터 삽입 코드를 분리
- 상위 30개 기업 데이터를 CompanyDataLoader에 추가 및 DataLoader에서 호출
<br/>
- 채용공고 테스트 데이터 추가
<br/>
<br/>

test: 기업, 채용공고 테스트 데이터 추가 및 분리

---

dev-route/build.gradle

- Gradle 8.10 환경에서 Copy에 대한 from, include, into가 인식되지 못하는 에러 발생
- 공식문서를 참고하여 코드를 수정
[Gradle 8.10 Copy](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html)
<br/>
- 인프라 배포 및 CI/CD 테스트
<br/>
<br/>

fix: gradle의 서브모듈 카피 코드 수정

---

dev-route/src/main/java/com/teamdevroute/devroute/global/config/TomcatConfig.java
dev-route/src/main/resources/application.properties

- Spring Boot가 X-Forwarded-* 헤더를 인식하도록 하며, 프록시나 로드 밸런서에서 전달되는 원래의 프로토콜을 기반으로 리다이렉트를 처리하게 합니다.
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

security: Tomca에서 https로 전달하도록 수정

---

dev-route/src/main/java/com/teamdevroute/devroute/crawling/CompanyRecruitmentCrawling.java

- `CompanyRecruitmentCrawling`의 `companyAndRecruitmentCrawling()`가 매월 1일 실행되도록 수정
```java
@Scheduled(cron = "0 0 0 1 * *", zone = "Asia/Seoul")
```
<br/>
<br/>
<br/>

fix: 채용공고 크롤링이 매월 1일에 실행되도록 수정

---

.github/workflows/deploy.yml
dev-route/src/main/java/com/teamdevroute/devroute/crawling/InfreanVideoCrawling.java

-  videocrawling 관련하여 리팩토링을 진행함
- 기존의 크롤링 메서드내에서 진행하던 정보추출을 다른 메서드를 만들어서, 해당 메서드의 테스트 코드를 따로 만들수 있도록 리팩토링 
-  기존의 불명확하던 변수명 변경
- 운영환경과 개발환경의 분리
- 기존에는 application-properties내에서 일일히 active=dev를 prod로 바꿔야지만, 해당 코드가 CI/CD가 적용될 때 운영환경의 db가 적용됨
-  현재는 docker가 빌드 될때 자동으로 application-prod.properties가 적용되어서, 개발환경과 운영환경의 분리가 보다 명확해짐
<br/>
- 내일 할 일을
- 적어주세요
<br/>
[ (issues/117)](https://github.com/ICT-Dev-Route/Dev-Route-BE/issues/117)
<br/>

Refactor: videocrawling 관련 리팩토링 및 CI/CD 배포시에 application-prod.propeties가 적용되게 설정

---

dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java

- 20분 정도 간격으로 CPU 사용량이 발생하는 것으로 확인
- 로그 확인 결과 해당 시간대에 EC2의 로드밸런서가 /healthcheck 경로로 헬스체크를 하게 된다.
- /healthcheck 경로에 대해 필터가 작용하는 것을 확인
<br/>
<br/>
<br/>

fix: /healthcheck 요청 시, 필터 통과하도록 설정

---

dev-route/src/main/java/com/teamdevroute/devroute/global/config/SecurityConfig.java

- Prometheus가 서버 정보를 못가져오는 오류 해결
- securityconfig에 있던 Whitelist내에서 url설정이 잘못되어있었음.
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

fix:Prometheus가 서버 정보를 못가져오는 오류 해결

---

dev-route/src/main/java/com/teamdevroute/devroute/company/domain/Company.java

- `RecruitmentUpdateService`의 `parseResponse()` 중 findByName의 결과가 다중 값이 나오는 문제가 발생
- 해당 문제를 해결하기 위해 Company의 name 필드를 unique=true로 수정
🔥기존에 입력된 데이터 중 이름 중복이 포함되어 Company와 Recruitment의 모든 데이터를 지우는 방향으로 추진 예정
<br/>
- 데이터 초기화
<br/>
[#125 ](https://github.com/ICT-Dev-Route/Dev-Route-BE/issues/125)
<br/>

fix: Company의 name 필드를 unique로 수정

---

dev-route/src/main/java/com/teamdevroute/devroute/recruitment/service/RecruitmentUpdateService.java

-  RecruitmentUpdateService내의 사람인 api를 다 가져왔는지를 반환하는 isMaxRequest 메서드 수정
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

fix: RecruitmentUpdateService내의 isMaxApiRequest 수정
